{
  "formatVersion": "1.1",
  "component": {
    "group": "com.improvertech",
    "module": "nativelan-android",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nativelan-android-0.0.7.aar",
          "url": "nativelan-android-0.0.7.aar",
          "size": 17530,
          "sha512": "4ac58ed0f489e815ed9aee27b67ef0a649b6a3e7d8d2188b5ec0d6643452e44d4d8b357572ece690cfd3d6e79722108060ae3ddcdd74d0d010fa80dd983c3dab",
          "sha256": "b781fe7144f5593daff519363fa38c15a657689c8e8537ece22b1ee6625d42d1",
          "sha1": "9d580efc8967e125797476d5856f1bc3a3294fc0",
          "md5": "daad39176c555f04de8d28b687574cf3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativelan-android-0.0.7.aar",
          "url": "nativelan-android-0.0.7.aar",
          "size": 17530,
          "sha512": "4ac58ed0f489e815ed9aee27b67ef0a649b6a3e7d8d2188b5ec0d6643452e44d4d8b357572ece690cfd3d6e79722108060ae3ddcdd74d0d010fa80dd983c3dab",
          "sha256": "b781fe7144f5593daff519363fa38c15a657689c8e8537ece22b1ee6625d42d1",
          "sha1": "9d580efc8967e125797476d5856f1bc3a3294fc0",
          "md5": "daad39176c555f04de8d28b687574cf3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nativelan-android-0.0.7-sources.jar",
          "url": "nativelan-android-0.0.7-sources.jar",
          "size": 6373,
          "sha512": "fac4108eafeaa2baf040b4fe85bed6ce467467f2f9fb272b12ff740766828d77b580f29ba0544dd3bc26bd99c8a9262afa5cbc257749a42621cb64ca13b2148e",
          "sha256": "bed1190fa959b532622ab993c1be6968b31b062d00eb281681a4d787848293fd",
          "sha1": "b0a128e693484da9221b0b4fc07bd8f7d34e50be",
          "md5": "2f2002d06c86d209df103b3e8e533817"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nativelan-android-0.0.7-javadoc.jar",
          "url": "nativelan-android-0.0.7-javadoc.jar",
          "size": 319596,
          "sha512": "5147584db9e64a1bbb4e6a64a68b209662c9636041956285820506644596017008335bae242b8cdb2797639a193c4a29f88b62446ef4032c90408612cb1ec260",
          "sha256": "82bb245b8c0d6ed008af30a0968624b3c876252379623681f8ede2a63708de4e",
          "sha1": "d1eb30a727965d01fca3e6f69b1e1aefe42325ef",
          "md5": "def334d49cc99d99f916db1fa589dd33"
        }
      ]
    }
  ]
}
