{
  "formatVersion": "1.1",
  "component": {
    "group": "com.improvertech",
    "module": "nativelan-android",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nativelan-android-0.0.5.aar",
          "url": "nativelan-android-0.0.5.aar",
          "size": 17201,
          "sha512": "7c731a169ed94c92a9c75f0e687eabb8bd5d9695c833581f40ba90777e7f695cbdf92c8e088fc968a97b76efb5963c6bd77ab636207e5842bab070868e5aeccc",
          "sha256": "a193680b378a95610c80da71efe43033724aae85b3bedf5ab4b1868f81ea8573",
          "sha1": "322706a64eb4a7a90a04f9259506b5538cad82f2",
          "md5": "a7fcad4e5e168cb7a6904b974db43e54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativelan-android-0.0.5.aar",
          "url": "nativelan-android-0.0.5.aar",
          "size": 17201,
          "sha512": "7c731a169ed94c92a9c75f0e687eabb8bd5d9695c833581f40ba90777e7f695cbdf92c8e088fc968a97b76efb5963c6bd77ab636207e5842bab070868e5aeccc",
          "sha256": "a193680b378a95610c80da71efe43033724aae85b3bedf5ab4b1868f81ea8573",
          "sha1": "322706a64eb4a7a90a04f9259506b5538cad82f2",
          "md5": "a7fcad4e5e168cb7a6904b974db43e54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nativelan-android-0.0.5-sources.jar",
          "url": "nativelan-android-0.0.5-sources.jar",
          "size": 6337,
          "sha512": "80a2d5cc7782871b4b0253ec85166347a9fefd8761341ac38509d21b05492bfc2d2f7a83e7e7b3035f8124985fc56e83fd7d6c8ad4a112a90fafb9a00ef12a5c",
          "sha256": "da3f98b658a6994b6db089a0e82f0d549f2c0db825e05c3dc556c30434f418f1",
          "sha1": "4fec99a98365beadee9446a874884d78e32958bd",
          "md5": "28692691268c58212ca1a6c908741a78"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nativelan-android-0.0.5-javadoc.jar",
          "url": "nativelan-android-0.0.5-javadoc.jar",
          "size": 319596,
          "sha512": "5147584db9e64a1bbb4e6a64a68b209662c9636041956285820506644596017008335bae242b8cdb2797639a193c4a29f88b62446ef4032c90408612cb1ec260",
          "sha256": "82bb245b8c0d6ed008af30a0968624b3c876252379623681f8ede2a63708de4e",
          "sha1": "d1eb30a727965d01fca3e6f69b1e1aefe42325ef",
          "md5": "def334d49cc99d99f916db1fa589dd33"
        }
      ]
    }
  ]
}
